{% set version = "0.8.3" %}

package:
  name: sqlx-cli
  version: {{ version }}

source:
  url: https://github.com/launchbadge/sqlx/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 35b1598670e6701021b2622dbc5e05acaba60ced5285b3fdc97b26910fed4bfb

build:
  number: 1

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [unix]

test:
  requires:
    - {{ compiler('rust') }}
  commands:
    - sqlx --version
    - sqlx --help
    - cargo sqlx --help

about:
  home: https://github.com/launchbadge/sqlx
  license: Apache-2.0
  summary: Command-line utility for SQLx, the Rust SQL toolkit.
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - borchero
    - danielnachun
