{% set version = "0.8.5" %}

package:
  name: sqlx-cli
  version: {{ version }}

source:
  url: https://github.com/launchbadge/sqlx/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c6a32bb7d733fd598ba7473da9f82e9971557302e180ca3da0b1e29028dc9027

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [unix]

test:
  requires:
    - {{ compiler('rust') }}
  commands:
    - sqlx --version
    - sqlx --help
    - cargo sqlx --help

about:
  home: https://github.com/launchbadge/sqlx
  license: Apache-2.0
  summary: Command-line utility for SQLx, the Rust SQL toolkit.
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - borchero
    - danielnachun
