{% set version = "0.8.0" %}

package:
  name: sqlx-cli
  version: {{ version }}

source:
  url: https://github.com/launchbadge/sqlx/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fffe09726fd225c0899c757bdbd5cad4481d63df6ca2f699a5aacd528cb01776

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [linux]
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [unix]

test:
  requires:
    - {{ compiler('rust') }}
  commands:
    - sqlx --version
    - sqlx --help
    - cargo sqlx --help

about:
  home: https://github.com/launchbadge/sqlx
  license: Apache-2.0
  license_family: Apache
  summary: Command-line utility for SQLx, the Rust SQL toolkit.
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - borchero
